// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: mkraxK26DVUcftaRqUY3yk
// Component: CvFzAVlSFBgi
import * as React from "react";

import * as p from "@plasmicapp/react-web";

import {
  hasVariant,
  classNames,
  wrapWithClassName,
  createPlasmicElementProxy,
  makeFragment,
  MultiChoiceArg,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  pick,
  omit,
  useTrigger,
  StrictProps,
  deriveRenderOpts,
  ensureGlobalVariants
} from "@plasmicapp/react-web";

import "@plasmicapp/react-web/lib/plasmic.css";
import * as defaultcss from "../plasmic__default_style.module.css"; // plasmic-import: global/defaultcss
import * as projectcss from "./plasmic_play_plasmic.module.css"; // plasmic-import: mkraxK26DVUcftaRqUY3yk/projectcss
import * as sty from "./PlasmicCompletedForecast.module.css"; // plasmic-import: CvFzAVlSFBgi/css

export type PlasmicCompletedForecast__VariantMembers = {
  variants: "tableRow";
};

export type PlasmicCompletedForecast__VariantsArgs = {
  variants?: SingleChoiceArg<"tableRow">;
};

type VariantPropType = keyof PlasmicCompletedForecast__VariantsArgs;
export const PlasmicCompletedForecast__VariantProps =
  new Array<VariantPropType>("variants");

export type PlasmicCompletedForecast__ArgsType = {
  children?: React.ReactNode;
};

type ArgPropType = keyof PlasmicCompletedForecast__ArgsType;
export const PlasmicCompletedForecast__ArgProps = new Array<ArgPropType>(
  "children"
);

export type PlasmicCompletedForecast__OverridesType = {
  root?: p.Flex<"div">;
  img?: p.Flex<typeof p.PlasmicImg>;
};

export interface DefaultCompletedForecastProps {
  children?: React.ReactNode;
  variants?: SingleChoiceArg<"tableRow">;
  className?: string;
}

function PlasmicCompletedForecast__RenderFunc(props: {
  variants: PlasmicCompletedForecast__VariantsArgs;
  args: PlasmicCompletedForecast__ArgsType;
  overrides: PlasmicCompletedForecast__OverridesType;
  dataFetches?: PlasmicCompletedForecast__Fetches;
  forNode?: string;
}) {
  const { variants, args, overrides, forNode, dataFetches } = props;

  return (
    <div
      data-plasmic-name={"root"}
      data-plasmic-override={overrides.root}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      className={classNames(
        defaultcss.all,
        projectcss.all,
        projectcss.root_reset,
        sty.root,
        {
          [sty.root__variants_tableRow]: hasVariant(
            variants,
            "variants",
            "tableRow"
          )
        }
      )}
    >
      <div
        className={classNames(
          defaultcss.all,
          projectcss.all,
          sty.freeBox___92Arz,
          {
            [sty.freeBox__variants_tableRow___92Arzjspp6]: hasVariant(
              variants,
              "variants",
              "tableRow"
            )
          }
        )}
      >
        {p.renderPlasmicSlot({
          defaultContents: "Wednesday",
          value: args.children,
          className: classNames(sty.slotTargetChildren, {
            [sty.slotTargetChildren__variants_tableRow]: hasVariant(
              variants,
              "variants",
              "tableRow"
            )
          })
        })}
      </div>

      <p.PlasmicImg
        data-plasmic-name={"img"}
        data-plasmic-override={overrides.img}
        alt={""}
        className={classNames(sty.img, {
          [sty.img__variants_tableRow]: hasVariant(
            variants,
            "variants",
            "tableRow"
          )
        })}
        displayHeight={"64px" as const}
        displayMaxHeight={"none" as const}
        displayMaxWidth={"none" as const}
        displayMinHeight={"0" as const}
        displayMinWidth={"0" as const}
        displayWidth={"64px" as const}
      />

      <p.Stack
        as={"div"}
        hasGap={true}
        className={classNames(
          defaultcss.all,
          projectcss.all,
          sty.freeBox__vbzHr,
          {
            [sty.freeBox__variants_tableRow__vbzHrjspp6]: hasVariant(
              variants,
              "variants",
              "tableRow"
            )
          }
        )}
      >
        <div
          className={classNames(
            defaultcss.all,
            projectcss.all,
            defaultcss.__wab_text,
            sty.text__tf5K9,
            {
              [sty.text__variants_tableRow__tf5K9Jspp6]: hasVariant(
                variants,
                "variants",
                "tableRow"
              )
            }
          )}
        >
          {"68°"}
        </div>

        <div
          className={classNames(
            defaultcss.all,
            projectcss.all,
            defaultcss.__wab_text,
            sty.text__tKwIz,
            {
              [sty.text__variants_tableRow__tKwIzJspp6]: hasVariant(
                variants,
                "variants",
                "tableRow"
              )
            }
          )}
        >
          {"36°"}
        </div>
      </p.Stack>

      <p.Stack
        as={"div"}
        hasGap={true}
        className={classNames(
          defaultcss.all,
          projectcss.all,
          sty.freeBox___83U2U,
          {
            [sty.freeBox__variants_tableRow___83U2Ujspp6]: hasVariant(
              variants,
              "variants",
              "tableRow"
            )
          }
        )}
      >
        <div
          className={classNames(
            defaultcss.all,
            projectcss.all,
            defaultcss.__wab_text,
            sty.text__bOqf4,
            {
              [sty.text__variants_tableRow__bOqf4Jspp6]: hasVariant(
                variants,
                "variants",
                "tableRow"
              )
            }
          )}
        >
          {"Pollen"}
        </div>

        <div
          className={classNames(
            defaultcss.all,
            projectcss.all,
            defaultcss.__wab_text,
            sty.text__z43JE,
            {
              [sty.text__variants_tableRow__z43JEjspp6]: hasVariant(
                variants,
                "variants",
                "tableRow"
              )
            }
          )}
        >
          {"35"}
        </div>
      </p.Stack>
    </div>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: ["root", "img"],
  img: ["img"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  typeof PlasmicDescendants[T][number];
type NodeDefaultElementType = {
  root: "div";
  img: typeof p.PlasmicImg;
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicCompletedForecast__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicCompletedForecast__VariantsArgs;
    args?: PlasmicCompletedForecast__ArgsType;
    overrides?: NodeOverridesType<T>;
    dataFetches?: PlasmicCompletedForecast__Fetches;
  } & Omit<PlasmicCompletedForecast__VariantsArgs, ReservedPropsType> & // Specify variants directly as props
    // Specify args directly as props
    Omit<PlasmicCompletedForecast__ArgsType, ReservedPropsType> &
    // Specify overrides for each element directly as props
    Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    // Specify props for the root element
    Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = deriveRenderOpts(props, {
      name: nodeName,
      descendantNames: [...PlasmicDescendants[nodeName]],
      internalArgPropNames: PlasmicCompletedForecast__ArgProps,
      internalVariantPropNames: PlasmicCompletedForecast__VariantProps
    });

    const { dataFetches } = props;

    return PlasmicCompletedForecast__RenderFunc({
      variants,
      args,
      overrides,
      dataFetches,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicCompletedForecast";
  } else {
    func.displayName = `PlasmicCompletedForecast.${nodeName}`;
  }
  return func;
}

export const PlasmicCompletedForecast = Object.assign(
  // Top-level PlasmicCompletedForecast renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    img: makeNodeComponent("img"),

    // Metadata about props expected for PlasmicCompletedForecast
    internalVariantProps: PlasmicCompletedForecast__VariantProps,
    internalArgProps: PlasmicCompletedForecast__ArgProps
  }
);

export default PlasmicCompletedForecast;
/* prettier-ignore-end */
