// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: mkraxK26DVUcftaRqUY3yk
// Component: 4Av6mv5Lu0DX
import * as React from "react";

import * as p from "@plasmicapp/react-web";

import {
  hasVariant,
  classNames,
  wrapWithClassName,
  createPlasmicElementProxy,
  makeFragment,
  MultiChoiceArg,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  pick,
  omit,
  useTrigger,
  StrictProps,
  deriveRenderOpts,
  ensureGlobalVariants
} from "@plasmicapp/react-web";

import "@plasmicapp/react-web/lib/plasmic.css";
import * as defaultcss from "../plasmic__default_style.module.css"; // plasmic-import: global/defaultcss
import * as projectcss from "./plasmic_play_plasmic.module.css"; // plasmic-import: mkraxK26DVUcftaRqUY3yk/projectcss
import * as sty from "./PlasmicBlockButton.module.css"; // plasmic-import: 4Av6mv5Lu0DX/css

import Icon20Icon from "./icons/PlasmicIcon__Icon20"; // plasmic-import: NX3vrnXXokrN/icon

export type PlasmicBlockButton__VariantMembers = {
  variants: "following";
};

export type PlasmicBlockButton__VariantsArgs = {
  variants?: SingleChoiceArg<"following">;
};

type VariantPropType = keyof PlasmicBlockButton__VariantsArgs;
export const PlasmicBlockButton__VariantProps = new Array<VariantPropType>(
  "variants"
);

export type PlasmicBlockButton__ArgsType = {};
type ArgPropType = keyof PlasmicBlockButton__ArgsType;
export const PlasmicBlockButton__ArgProps = new Array<ArgPropType>();

export type PlasmicBlockButton__OverridesType = {
  root?: p.Flex<"div">;
  svg?: p.Flex<"svg">;
  text?: p.Flex<"div">;
};

export interface DefaultBlockButtonProps {
  variants?: SingleChoiceArg<"following">;
  className?: string;
}

function PlasmicBlockButton__RenderFunc(props: {
  variants: PlasmicBlockButton__VariantsArgs;
  args: PlasmicBlockButton__ArgsType;
  overrides: PlasmicBlockButton__OverridesType;
  dataFetches?: PlasmicBlockButton__Fetches;
  forNode?: string;
}) {
  const { variants, args, overrides, forNode, dataFetches } = props;

  return (
    <p.Stack
      as={"div"}
      data-plasmic-name={"root"}
      data-plasmic-override={overrides.root}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      hasGap={true}
      className={classNames(
        defaultcss.all,
        projectcss.all,
        projectcss.root_reset,
        sty.root,
        {
          [sty.root__variants_following]: hasVariant(
            variants,
            "variants",
            "following"
          )
        }
      )}
    >
      <Icon20Icon
        data-plasmic-name={"svg"}
        data-plasmic-override={overrides.svg}
        className={classNames(defaultcss.all, projectcss.all, sty.svg, {
          [sty.svg__variants_following]: hasVariant(
            variants,
            "variants",
            "following"
          )
        })}
        role={"img"}
      />

      <div
        data-plasmic-name={"text"}
        data-plasmic-override={overrides.text}
        className={classNames(
          defaultcss.all,
          projectcss.all,
          defaultcss.__wab_text,
          sty.text,
          {
            [sty.text__variants_following]: hasVariant(
              variants,
              "variants",
              "following"
            )
          }
        )}
      >
        {"Block"}
      </div>
    </p.Stack>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: ["root", "svg", "text"],
  svg: ["svg"],
  text: ["text"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  typeof PlasmicDescendants[T][number];
type NodeDefaultElementType = {
  root: "div";
  svg: "svg";
  text: "div";
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicBlockButton__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicBlockButton__VariantsArgs;
    args?: PlasmicBlockButton__ArgsType;
    overrides?: NodeOverridesType<T>;
    dataFetches?: PlasmicBlockButton__Fetches;
  } & Omit<PlasmicBlockButton__VariantsArgs, ReservedPropsType> & // Specify variants directly as props
    // Specify args directly as props
    Omit<PlasmicBlockButton__ArgsType, ReservedPropsType> &
    // Specify overrides for each element directly as props
    Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    // Specify props for the root element
    Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = deriveRenderOpts(props, {
      name: nodeName,
      descendantNames: [...PlasmicDescendants[nodeName]],
      internalArgPropNames: PlasmicBlockButton__ArgProps,
      internalVariantPropNames: PlasmicBlockButton__VariantProps
    });

    const { dataFetches } = props;

    return PlasmicBlockButton__RenderFunc({
      variants,
      args,
      overrides,
      dataFetches,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicBlockButton";
  } else {
    func.displayName = `PlasmicBlockButton.${nodeName}`;
  }
  return func;
}

export const PlasmicBlockButton = Object.assign(
  // Top-level PlasmicBlockButton renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    svg: makeNodeComponent("svg"),
    text: makeNodeComponent("text"),

    // Metadata about props expected for PlasmicBlockButton
    internalVariantProps: PlasmicBlockButton__VariantProps,
    internalArgProps: PlasmicBlockButton__ArgProps
  }
);

export default PlasmicBlockButton;
/* prettier-ignore-end */
