// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: mkraxK26DVUcftaRqUY3yk
// Component: jexBH1CRCuKl
import * as React from "react";

import * as p from "@plasmicapp/react-web";

import {
  hasVariant,
  classNames,
  wrapWithClassName,
  createPlasmicElementProxy,
  makeFragment,
  MultiChoiceArg,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  pick,
  omit,
  useTrigger,
  StrictProps,
  deriveRenderOpts,
  ensureGlobalVariants
} from "@plasmicapp/react-web";

import "@plasmicapp/react-web/lib/plasmic.css";
import * as defaultcss from "../plasmic__default_style.module.css"; // plasmic-import: global/defaultcss
import * as projectcss from "./plasmic_play_plasmic.module.css"; // plasmic-import: mkraxK26DVUcftaRqUY3yk/projectcss
import * as sty from "./PlasmicWorkspaceLabel.module.css"; // plasmic-import: jexBH1CRCuKl/css

export type PlasmicWorkspaceLabel__VariantMembers = {};

export type PlasmicWorkspaceLabel__VariantsArgs = {};
type VariantPropType = keyof PlasmicWorkspaceLabel__VariantsArgs;
export const PlasmicWorkspaceLabel__VariantProps = new Array<VariantPropType>();

export type PlasmicWorkspaceLabel__ArgsType = {
  children?: React.ReactNode;
};

type ArgPropType = keyof PlasmicWorkspaceLabel__ArgsType;
export const PlasmicWorkspaceLabel__ArgProps = new Array<ArgPropType>(
  "children"
);

export type PlasmicWorkspaceLabel__OverridesType = {
  root?: p.Flex<"div">;
  freeBox?: p.Flex<"div">;
};

export interface DefaultWorkspaceLabelProps {
  children?: React.ReactNode;
  className?: string;
}

function PlasmicWorkspaceLabel__RenderFunc(props: {
  variants: PlasmicWorkspaceLabel__VariantsArgs;
  args: PlasmicWorkspaceLabel__ArgsType;
  overrides: PlasmicWorkspaceLabel__OverridesType;
  dataFetches?: PlasmicWorkspaceLabel__Fetches;
  forNode?: string;
}) {
  const { variants, args, overrides, forNode, dataFetches } = props;

  return (
    <div
      data-plasmic-name={"root"}
      data-plasmic-override={overrides.root}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      className={classNames(
        defaultcss.all,
        projectcss.all,
        projectcss.root_reset,
        sty.root
      )}
    >
      <div
        data-plasmic-name={"freeBox"}
        data-plasmic-override={overrides.freeBox}
        className={classNames(defaultcss.all, projectcss.all, sty.freeBox)}
      >
        {p.renderPlasmicSlot({
          defaultContents: "Objective:",
          value: args.children,
          className: classNames(sty.slotTargetChildren)
        })}
      </div>
    </div>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: ["root", "freeBox"],
  freeBox: ["freeBox"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  typeof PlasmicDescendants[T][number];
type NodeDefaultElementType = {
  root: "div";
  freeBox: "div";
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicWorkspaceLabel__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicWorkspaceLabel__VariantsArgs;
    args?: PlasmicWorkspaceLabel__ArgsType;
    overrides?: NodeOverridesType<T>;
    dataFetches?: PlasmicWorkspaceLabel__Fetches;
  } & Omit<PlasmicWorkspaceLabel__VariantsArgs, ReservedPropsType> & // Specify variants directly as props
    // Specify args directly as props
    Omit<PlasmicWorkspaceLabel__ArgsType, ReservedPropsType> &
    // Specify overrides for each element directly as props
    Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    // Specify props for the root element
    Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = deriveRenderOpts(props, {
      name: nodeName,
      descendantNames: [...PlasmicDescendants[nodeName]],
      internalArgPropNames: PlasmicWorkspaceLabel__ArgProps,
      internalVariantPropNames: PlasmicWorkspaceLabel__VariantProps
    });

    const { dataFetches } = props;

    return PlasmicWorkspaceLabel__RenderFunc({
      variants,
      args,
      overrides,
      dataFetches,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicWorkspaceLabel";
  } else {
    func.displayName = `PlasmicWorkspaceLabel.${nodeName}`;
  }
  return func;
}

export const PlasmicWorkspaceLabel = Object.assign(
  // Top-level PlasmicWorkspaceLabel renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    freeBox: makeNodeComponent("freeBox"),

    // Metadata about props expected for PlasmicWorkspaceLabel
    internalVariantProps: PlasmicWorkspaceLabel__VariantProps,
    internalArgProps: PlasmicWorkspaceLabel__ArgProps
  }
);

export default PlasmicWorkspaceLabel;
/* prettier-ignore-end */
