// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: mkraxK26DVUcftaRqUY3yk
// Component: T-MoYnpvR__u
import * as React from "react";

import * as p from "@plasmicapp/react-web";

import {
  hasVariant,
  classNames,
  wrapWithClassName,
  createPlasmicElementProxy,
  makeFragment,
  MultiChoiceArg,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  pick,
  omit,
  useTrigger,
  StrictProps,
  deriveRenderOpts,
  ensureGlobalVariants
} from "@plasmicapp/react-web";

import "@plasmicapp/react-web/lib/plasmic.css";
import * as defaultcss from "../plasmic__default_style.module.css"; // plasmic-import: global/defaultcss
import * as projectcss from "./plasmic_play_plasmic.module.css"; // plasmic-import: mkraxK26DVUcftaRqUY3yk/projectcss
import * as sty from "./PlasmicAccentSwitch.module.css"; // plasmic-import: T-MoYnpvR__u/css

export type PlasmicAccentSwitch__VariantMembers = {};

export type PlasmicAccentSwitch__VariantsArgs = {};
type VariantPropType = keyof PlasmicAccentSwitch__VariantsArgs;
export const PlasmicAccentSwitch__VariantProps = new Array<VariantPropType>();

export type PlasmicAccentSwitch__ArgsType = {};
type ArgPropType = keyof PlasmicAccentSwitch__ArgsType;
export const PlasmicAccentSwitch__ArgProps = new Array<ArgPropType>();

export type PlasmicAccentSwitch__OverridesType = {
  root?: p.Flex<"div">;
  freeBox?: p.Flex<"div">;
};

export interface DefaultAccentSwitchProps {
  className?: string;
}

function PlasmicAccentSwitch__RenderFunc(props: {
  variants: PlasmicAccentSwitch__VariantsArgs;
  args: PlasmicAccentSwitch__ArgsType;
  overrides: PlasmicAccentSwitch__OverridesType;
  dataFetches?: PlasmicAccentSwitch__Fetches;
  forNode?: string;
}) {
  const { variants, args, overrides, forNode, dataFetches } = props;

  return (
    <div
      data-plasmic-name={"root"}
      data-plasmic-override={overrides.root}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      className={classNames(
        defaultcss.all,
        projectcss.all,
        projectcss.root_reset,
        sty.root
      )}
    >
      <div
        data-plasmic-name={"freeBox"}
        data-plasmic-override={overrides.freeBox}
        className={classNames(defaultcss.all, projectcss.all, sty.freeBox)}
      />
    </div>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: ["root", "freeBox"],
  freeBox: ["freeBox"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  typeof PlasmicDescendants[T][number];
type NodeDefaultElementType = {
  root: "div";
  freeBox: "div";
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicAccentSwitch__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicAccentSwitch__VariantsArgs;
    args?: PlasmicAccentSwitch__ArgsType;
    overrides?: NodeOverridesType<T>;
    dataFetches?: PlasmicAccentSwitch__Fetches;
  } & Omit<PlasmicAccentSwitch__VariantsArgs, ReservedPropsType> & // Specify variants directly as props
    // Specify args directly as props
    Omit<PlasmicAccentSwitch__ArgsType, ReservedPropsType> &
    // Specify overrides for each element directly as props
    Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    // Specify props for the root element
    Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = deriveRenderOpts(props, {
      name: nodeName,
      descendantNames: [...PlasmicDescendants[nodeName]],
      internalArgPropNames: PlasmicAccentSwitch__ArgProps,
      internalVariantPropNames: PlasmicAccentSwitch__VariantProps
    });

    const { dataFetches } = props;

    return PlasmicAccentSwitch__RenderFunc({
      variants,
      args,
      overrides,
      dataFetches,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicAccentSwitch";
  } else {
    func.displayName = `PlasmicAccentSwitch.${nodeName}`;
  }
  return func;
}

export const PlasmicAccentSwitch = Object.assign(
  // Top-level PlasmicAccentSwitch renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    freeBox: makeNodeComponent("freeBox"),

    // Metadata about props expected for PlasmicAccentSwitch
    internalVariantProps: PlasmicAccentSwitch__VariantProps,
    internalArgProps: PlasmicAccentSwitch__ArgProps
  }
);

export default PlasmicAccentSwitch;
/* prettier-ignore-end */
