// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: mkraxK26DVUcftaRqUY3yk
// Component: r3AiXoRjgPgA
import * as React from "react";

import * as p from "@plasmicapp/react-web";

import {
  hasVariant,
  classNames,
  wrapWithClassName,
  createPlasmicElementProxy,
  makeFragment,
  MultiChoiceArg,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  pick,
  omit,
  useTrigger,
  StrictProps,
  deriveRenderOpts,
  ensureGlobalVariants
} from "@plasmicapp/react-web";

import "@plasmicapp/react-web/lib/plasmic.css";
import * as defaultcss from "../plasmic__default_style.module.css"; // plasmic-import: global/defaultcss
import * as projectcss from "./plasmic_play_plasmic.module.css"; // plasmic-import: mkraxK26DVUcftaRqUY3yk/projectcss
import * as sty from "./PlasmicDualSizeProfile.module.css"; // plasmic-import: r3AiXoRjgPgA/css

import image11PtgN1IMRoBf from "./images/image11.png"; // plasmic-import: PtgN1I-mROBf/picture

export type PlasmicDualSizeProfile__VariantMembers = {
  expanded: "expanded";
};

export type PlasmicDualSizeProfile__VariantsArgs = {
  expanded?: SingleBooleanChoiceArg<"expanded">;
};

type VariantPropType = keyof PlasmicDualSizeProfile__VariantsArgs;
export const PlasmicDualSizeProfile__VariantProps = new Array<VariantPropType>(
  "expanded"
);

export type PlasmicDualSizeProfile__ArgsType = {};
type ArgPropType = keyof PlasmicDualSizeProfile__ArgsType;
export const PlasmicDualSizeProfile__ArgProps = new Array<ArgPropType>();

export type PlasmicDualSizeProfile__OverridesType = {
  root?: p.Flex<"div">;
  img?: p.Flex<typeof p.PlasmicImg>;
  freeBox?: p.Flex<"div">;
};

export interface DefaultDualSizeProfileProps {
  expanded?: SingleBooleanChoiceArg<"expanded">;
  className?: string;
}

function PlasmicDualSizeProfile__RenderFunc(props: {
  variants: PlasmicDualSizeProfile__VariantsArgs;
  args: PlasmicDualSizeProfile__ArgsType;
  overrides: PlasmicDualSizeProfile__OverridesType;
  dataFetches?: PlasmicDualSizeProfile__Fetches;
  forNode?: string;
}) {
  const { variants, args, overrides, forNode, dataFetches } = props;

  return (
    <p.Stack
      as={"div"}
      data-plasmic-name={"root"}
      data-plasmic-override={overrides.root}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      hasGap={true}
      className={classNames(
        defaultcss.all,
        projectcss.all,
        projectcss.root_reset,
        sty.root,
        { [sty.root__expanded]: hasVariant(variants, "expanded", "expanded") }
      )}
    >
      <p.PlasmicImg
        data-plasmic-name={"img"}
        data-plasmic-override={overrides.img}
        alt={""}
        className={classNames(sty.img, {
          [sty.img__expanded]: hasVariant(variants, "expanded", "expanded")
        })}
        displayHeight={"50px" as const}
        displayMaxHeight={"none" as const}
        displayMaxWidth={"none" as const}
        displayMinHeight={"0" as const}
        displayMinWidth={"0" as const}
        displayWidth={"50px" as const}
        src={{
          src: image11PtgN1IMRoBf,
          fullWidth: 150,
          fullHeight: 184,
          aspectRatio: undefined
        }}
      />

      <p.Stack
        as={"div"}
        data-plasmic-name={"freeBox"}
        data-plasmic-override={overrides.freeBox}
        hasGap={true}
        className={classNames(defaultcss.all, projectcss.all, sty.freeBox, {
          [sty.freeBox__expanded]: hasVariant(variants, "expanded", "expanded")
        })}
      >
        <div
          className={classNames(
            defaultcss.all,
            projectcss.all,
            defaultcss.__wab_text,
            sty.text__ieMpF,
            {
              [sty.text__expanded__ieMpF6AwUa]: hasVariant(
                variants,
                "expanded",
                "expanded"
              )
            }
          )}
        >
          {"Totoro"}
        </div>

        <div
          className={classNames(
            defaultcss.all,
            projectcss.all,
            defaultcss.__wab_text,
            sty.text__zTm91,
            {
              [sty.text__expanded__zTm916AwUa]: hasVariant(
                variants,
                "expanded",
                "expanded"
              )
            }
          )}
        >
          {"@friendlyneighbor"}
        </div>
      </p.Stack>
    </p.Stack>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: ["root", "img", "freeBox"],
  img: ["img"],
  freeBox: ["freeBox"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  typeof PlasmicDescendants[T][number];
type NodeDefaultElementType = {
  root: "div";
  img: typeof p.PlasmicImg;
  freeBox: "div";
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicDualSizeProfile__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicDualSizeProfile__VariantsArgs;
    args?: PlasmicDualSizeProfile__ArgsType;
    overrides?: NodeOverridesType<T>;
    dataFetches?: PlasmicDualSizeProfile__Fetches;
  } & Omit<PlasmicDualSizeProfile__VariantsArgs, ReservedPropsType> & // Specify variants directly as props
    // Specify args directly as props
    Omit<PlasmicDualSizeProfile__ArgsType, ReservedPropsType> &
    // Specify overrides for each element directly as props
    Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    // Specify props for the root element
    Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = deriveRenderOpts(props, {
      name: nodeName,
      descendantNames: [...PlasmicDescendants[nodeName]],
      internalArgPropNames: PlasmicDualSizeProfile__ArgProps,
      internalVariantPropNames: PlasmicDualSizeProfile__VariantProps
    });

    const { dataFetches } = props;

    return PlasmicDualSizeProfile__RenderFunc({
      variants,
      args,
      overrides,
      dataFetches,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicDualSizeProfile";
  } else {
    func.displayName = `PlasmicDualSizeProfile.${nodeName}`;
  }
  return func;
}

export const PlasmicDualSizeProfile = Object.assign(
  // Top-level PlasmicDualSizeProfile renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    img: makeNodeComponent("img"),
    freeBox: makeNodeComponent("freeBox"),

    // Metadata about props expected for PlasmicDualSizeProfile
    internalVariantProps: PlasmicDualSizeProfile__VariantProps,
    internalArgProps: PlasmicDualSizeProfile__ArgProps
  }
);

export default PlasmicDualSizeProfile;
/* prettier-ignore-end */
