// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: mkraxK26DVUcftaRqUY3yk
// Component: nIf4RF0JY0hs
import * as React from "react";

import * as p from "@plasmicapp/react-web";

import {
  hasVariant,
  classNames,
  wrapWithClassName,
  createPlasmicElementProxy,
  makeFragment,
  MultiChoiceArg,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  pick,
  omit,
  useTrigger,
  StrictProps,
  deriveRenderOpts,
  ensureGlobalVariants
} from "@plasmicapp/react-web";

import "@plasmicapp/react-web/lib/plasmic.css";
import * as defaultcss from "../plasmic__default_style.module.css"; // plasmic-import: global/defaultcss
import * as projectcss from "./plasmic_play_plasmic.module.css"; // plasmic-import: mkraxK26DVUcftaRqUY3yk/projectcss
import * as sty from "./PlasmicLandmarks.module.css"; // plasmic-import: nIf4RF0JY0hs/css

import Icon12Icon from "./icons/PlasmicIcon__Icon12"; // plasmic-import: nPmRp3GbB80G/icon

export type PlasmicLandmarks__VariantMembers = {
  variants: "wide";
};

export type PlasmicLandmarks__VariantsArgs = {
  variants?: SingleChoiceArg<"wide">;
};

type VariantPropType = keyof PlasmicLandmarks__VariantsArgs;
export const PlasmicLandmarks__VariantProps = new Array<VariantPropType>(
  "variants"
);

export type PlasmicLandmarks__ArgsType = {};
type ArgPropType = keyof PlasmicLandmarks__ArgsType;
export const PlasmicLandmarks__ArgProps = new Array<ArgPropType>();

export type PlasmicLandmarks__OverridesType = {
  root?: p.Flex<"div">;
};

export interface DefaultLandmarksProps {
  variants?: SingleChoiceArg<"wide">;
  className?: string;
}

function PlasmicLandmarks__RenderFunc(props: {
  variants: PlasmicLandmarks__VariantsArgs;
  args: PlasmicLandmarks__ArgsType;
  overrides: PlasmicLandmarks__OverridesType;
  dataFetches?: PlasmicLandmarks__Fetches;
  forNode?: string;
}) {
  const { variants, args, overrides, forNode, dataFetches } = props;

  return (
    <div
      data-plasmic-name={"root"}
      data-plasmic-override={overrides.root}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      className={classNames(
        defaultcss.all,
        projectcss.all,
        projectcss.root_reset,
        sty.root,
        { [sty.root__variants_wide]: hasVariant(variants, "variants", "wide") }
      )}
    >
      <div
        className={classNames(
          defaultcss.all,
          projectcss.all,
          defaultcss.__wab_text,
          sty.text___2XaLf,
          {
            [sty.text__variants_wide___2XaLfA88GQ]: hasVariant(
              variants,
              "variants",
              "wide"
            )
          }
        )}
      >
        {"Landmarks"}
      </div>

      <p.Stack
        as={"div"}
        hasGap={true}
        className={classNames(
          defaultcss.all,
          projectcss.all,
          sty.freeBox__lk5NM,
          {
            [sty.freeBox__variants_wide__lk5NMa88GQ]: hasVariant(
              variants,
              "variants",
              "wide"
            )
          }
        )}
      >
        <div
          className={classNames(
            defaultcss.all,
            projectcss.all,
            sty.freeBox__s6RMc,
            {
              [sty.freeBox__variants_wide__s6RMcA88GQ]: hasVariant(
                variants,
                "variants",
                "wide"
              )
            }
          )}
        >
          <div
            className={classNames(
              defaultcss.all,
              projectcss.all,
              defaultcss.__wab_text,
              sty.text__uN7Kh
            )}
          >
            {"Mission Dolores Park"}
          </div>

          <div
            className={classNames(
              defaultcss.all,
              projectcss.all,
              defaultcss.__wab_text,
              sty.text__bCjTk
            )}
          >
            {"Park"}
          </div>

          <Icon12Icon
            className={classNames(
              defaultcss.all,
              projectcss.all,
              sty.svg__fRliU
            )}
            role={"img"}
          />
        </div>

        <div
          className={classNames(
            defaultcss.all,
            projectcss.all,
            sty.freeBox__cqYCy,
            {
              [sty.freeBox__variants_wide__cqYCyA88GQ]: hasVariant(
                variants,
                "variants",
                "wide"
              )
            }
          )}
        >
          <div
            className={classNames(
              defaultcss.all,
              projectcss.all,
              defaultcss.__wab_text,
              sty.text__w4LXm,
              {
                [sty.text__variants_wide__w4LXmA88GQ]: hasVariant(
                  variants,
                  "variants",
                  "wide"
                )
              }
            )}
          >
            {"Mission Dolores Park"}
          </div>

          <div
            className={classNames(
              defaultcss.all,
              projectcss.all,
              defaultcss.__wab_text,
              sty.text___4TsM3
            )}
          >
            {"Park"}
          </div>

          <Icon12Icon
            className={classNames(
              defaultcss.all,
              projectcss.all,
              sty.svg__v3Cq5
            )}
            role={"img"}
          />
        </div>

        <div
          className={classNames(
            defaultcss.all,
            projectcss.all,
            sty.freeBox__su1I0,
            {
              [sty.freeBox__variants_wide__su1I0A88GQ]: hasVariant(
                variants,
                "variants",
                "wide"
              )
            }
          )}
        >
          <div
            className={classNames(
              defaultcss.all,
              projectcss.all,
              defaultcss.__wab_text,
              sty.text__qion1
            )}
          >
            {"Mission Dolores Park"}
          </div>

          <div
            className={classNames(
              defaultcss.all,
              projectcss.all,
              defaultcss.__wab_text,
              sty.text___9CGok
            )}
          >
            {"Park"}
          </div>

          <Icon12Icon
            className={classNames(
              defaultcss.all,
              projectcss.all,
              sty.svg___7Oe6
            )}
            role={"img"}
          />
        </div>
      </p.Stack>
    </div>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: ["root"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  typeof PlasmicDescendants[T][number];
type NodeDefaultElementType = {
  root: "div";
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicLandmarks__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicLandmarks__VariantsArgs;
    args?: PlasmicLandmarks__ArgsType;
    overrides?: NodeOverridesType<T>;
    dataFetches?: PlasmicLandmarks__Fetches;
  } & Omit<PlasmicLandmarks__VariantsArgs, ReservedPropsType> & // Specify variants directly as props
    // Specify args directly as props
    Omit<PlasmicLandmarks__ArgsType, ReservedPropsType> &
    // Specify overrides for each element directly as props
    Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    // Specify props for the root element
    Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = deriveRenderOpts(props, {
      name: nodeName,
      descendantNames: [...PlasmicDescendants[nodeName]],
      internalArgPropNames: PlasmicLandmarks__ArgProps,
      internalVariantPropNames: PlasmicLandmarks__VariantProps
    });

    const { dataFetches } = props;

    return PlasmicLandmarks__RenderFunc({
      variants,
      args,
      overrides,
      dataFetches,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicLandmarks";
  } else {
    func.displayName = `PlasmicLandmarks.${nodeName}`;
  }
  return func;
}

export const PlasmicLandmarks = Object.assign(
  // Top-level PlasmicLandmarks renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements

    // Metadata about props expected for PlasmicLandmarks
    internalVariantProps: PlasmicLandmarks__VariantProps,
    internalArgProps: PlasmicLandmarks__ArgProps
  }
);

export default PlasmicLandmarks;
/* prettier-ignore-end */
