// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: mkraxK26DVUcftaRqUY3yk
// Component: kMQuPQO47B29
import * as React from "react";

import * as p from "@plasmicapp/react-web";

import {
  hasVariant,
  classNames,
  wrapWithClassName,
  createPlasmicElementProxy,
  makeFragment,
  MultiChoiceArg,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  pick,
  omit,
  useTrigger,
  StrictProps,
  deriveRenderOpts,
  ensureGlobalVariants
} from "@plasmicapp/react-web";
import WorkspaceLabel from "../../WorkspaceLabel"; // plasmic-import: jexBH1CRCuKl/component

import "@plasmicapp/react-web/lib/plasmic.css";
import * as defaultcss from "../plasmic__default_style.module.css"; // plasmic-import: global/defaultcss
import * as projectcss from "./plasmic_play_plasmic.module.css"; // plasmic-import: mkraxK26DVUcftaRqUY3yk/projectcss
import * as sty from "./PlasmicTryItHere.module.css"; // plasmic-import: kMQuPQO47B29/css

export type PlasmicTryItHere__VariantMembers = {};

export type PlasmicTryItHere__VariantsArgs = {};
type VariantPropType = keyof PlasmicTryItHere__VariantsArgs;
export const PlasmicTryItHere__VariantProps = new Array<VariantPropType>();

export type PlasmicTryItHere__ArgsType = {};
type ArgPropType = keyof PlasmicTryItHere__ArgsType;
export const PlasmicTryItHere__ArgProps = new Array<ArgPropType>();

export type PlasmicTryItHere__OverridesType = {
  root?: p.Flex<typeof WorkspaceLabel>;
  text?: p.Flex<"div">;
};

export interface DefaultTryItHereProps {
  className?: string;
}

function PlasmicTryItHere__RenderFunc(props: {
  variants: PlasmicTryItHere__VariantsArgs;
  args: PlasmicTryItHere__ArgsType;
  overrides: PlasmicTryItHere__OverridesType;
  dataFetches?: PlasmicTryItHere__Fetches;
  forNode?: string;
}) {
  const { variants, args, overrides, forNode, dataFetches } = props;

  return (
    <WorkspaceLabel
      data-plasmic-name={"root"}
      data-plasmic-override={overrides.root}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      className={classNames("__wab_instance", sty.root)}
    >
      <div
        data-plasmic-name={"text"}
        data-plasmic-override={overrides.text}
        className={classNames(
          defaultcss.all,
          projectcss.all,
          defaultcss.__wab_text,
          sty.text
        )}
      >
        {"Try it here:"}
      </div>
    </WorkspaceLabel>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: ["root", "text"],
  text: ["text"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  typeof PlasmicDescendants[T][number];
type NodeDefaultElementType = {
  root: typeof WorkspaceLabel;
  text: "div";
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicTryItHere__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicTryItHere__VariantsArgs;
    args?: PlasmicTryItHere__ArgsType;
    overrides?: NodeOverridesType<T>;
    dataFetches?: PlasmicTryItHere__Fetches;
  } & Omit<PlasmicTryItHere__VariantsArgs, ReservedPropsType> & // Specify variants directly as props
    // Specify args directly as props
    Omit<PlasmicTryItHere__ArgsType, ReservedPropsType> &
    // Specify overrides for each element directly as props
    Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    // Specify props for the root element
    Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = deriveRenderOpts(props, {
      name: nodeName,
      descendantNames: [...PlasmicDescendants[nodeName]],
      internalArgPropNames: PlasmicTryItHere__ArgProps,
      internalVariantPropNames: PlasmicTryItHere__VariantProps
    });

    const { dataFetches } = props;

    return PlasmicTryItHere__RenderFunc({
      variants,
      args,
      overrides,
      dataFetches,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicTryItHere";
  } else {
    func.displayName = `PlasmicTryItHere.${nodeName}`;
  }
  return func;
}

export const PlasmicTryItHere = Object.assign(
  // Top-level PlasmicTryItHere renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    text: makeNodeComponent("text"),

    // Metadata about props expected for PlasmicTryItHere
    internalVariantProps: PlasmicTryItHere__VariantProps,
    internalArgProps: PlasmicTryItHere__ArgProps
  }
);

export default PlasmicTryItHere;
/* prettier-ignore-end */
