// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: mkraxK26DVUcftaRqUY3yk
// Component: MI4njOrUzq-E
import * as React from "react";

import * as p from "@plasmicapp/react-web";

import {
  hasVariant,
  classNames,
  wrapWithClassName,
  createPlasmicElementProxy,
  makeFragment,
  MultiChoiceArg,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  pick,
  omit,
  useTrigger,
  StrictProps,
  deriveRenderOpts,
  ensureGlobalVariants
} from "@plasmicapp/react-web";
import Bullet from "../../Bullet"; // plasmic-import: JmB_xgrb8cmb/component

import "@plasmicapp/react-web/lib/plasmic.css";
import * as defaultcss from "../plasmic__default_style.module.css"; // plasmic-import: global/defaultcss
import * as projectcss from "./plasmic_play_plasmic.module.css"; // plasmic-import: mkraxK26DVUcftaRqUY3yk/projectcss
import * as sty from "./PlasmicBulletItem.module.css"; // plasmic-import: MI4njOrUzq-E/css

export type PlasmicBulletItem__VariantMembers = {};

export type PlasmicBulletItem__VariantsArgs = {};
type VariantPropType = keyof PlasmicBulletItem__VariantsArgs;
export const PlasmicBulletItem__VariantProps = new Array<VariantPropType>();

export type PlasmicBulletItem__ArgsType = {
  children?: React.ReactNode;
  slot?: React.ReactNode;
};

type ArgPropType = keyof PlasmicBulletItem__ArgsType;
export const PlasmicBulletItem__ArgProps = new Array<ArgPropType>(
  "children",
  "slot"
);

export type PlasmicBulletItem__OverridesType = {
  root?: p.Flex<"div">;
  bullet?: p.Flex<typeof Bullet>;
};

export interface DefaultBulletItemProps {
  children?: React.ReactNode;
  slot?: React.ReactNode;
  className?: string;
}

function PlasmicBulletItem__RenderFunc(props: {
  variants: PlasmicBulletItem__VariantsArgs;
  args: PlasmicBulletItem__ArgsType;
  overrides: PlasmicBulletItem__OverridesType;
  dataFetches?: PlasmicBulletItem__Fetches;
  forNode?: string;
}) {
  const { variants, args, overrides, forNode, dataFetches } = props;

  return (
    <div
      data-plasmic-name={"root"}
      data-plasmic-override={overrides.root}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      className={classNames(
        defaultcss.all,
        projectcss.all,
        projectcss.root_reset,
        sty.root
      )}
    >
      <Bullet
        data-plasmic-name={"bullet"}
        data-plasmic-override={overrides.bullet}
        className={classNames("__wab_instance", sty.bullet)}
      >
        {p.renderPlasmicSlot({
          defaultContents: "•",
          value: args.slot
        })}
      </Bullet>

      <div
        className={classNames(
          defaultcss.all,
          projectcss.all,
          sty.freeBox__ocmB2
        )}
      >
        <div
          className={classNames(
            defaultcss.all,
            projectcss.all,
            sty.freeBox__fhHWn
          )}
        >
          {p.renderPlasmicSlot({
            defaultContents:
              "You can always press Cmd+Z to undo if you mess up.",
            value: args.children,
            className: classNames(sty.slotTargetChildren)
          })}
        </div>
      </div>
    </div>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: ["root", "bullet"],
  bullet: ["bullet"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  typeof PlasmicDescendants[T][number];
type NodeDefaultElementType = {
  root: "div";
  bullet: typeof Bullet;
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicBulletItem__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicBulletItem__VariantsArgs;
    args?: PlasmicBulletItem__ArgsType;
    overrides?: NodeOverridesType<T>;
    dataFetches?: PlasmicBulletItem__Fetches;
  } & Omit<PlasmicBulletItem__VariantsArgs, ReservedPropsType> & // Specify variants directly as props
    // Specify args directly as props
    Omit<PlasmicBulletItem__ArgsType, ReservedPropsType> &
    // Specify overrides for each element directly as props
    Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    // Specify props for the root element
    Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = deriveRenderOpts(props, {
      name: nodeName,
      descendantNames: [...PlasmicDescendants[nodeName]],
      internalArgPropNames: PlasmicBulletItem__ArgProps,
      internalVariantPropNames: PlasmicBulletItem__VariantProps
    });

    const { dataFetches } = props;

    return PlasmicBulletItem__RenderFunc({
      variants,
      args,
      overrides,
      dataFetches,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicBulletItem";
  } else {
    func.displayName = `PlasmicBulletItem.${nodeName}`;
  }
  return func;
}

export const PlasmicBulletItem = Object.assign(
  // Top-level PlasmicBulletItem renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    bullet: makeNodeComponent("bullet"),

    // Metadata about props expected for PlasmicBulletItem
    internalVariantProps: PlasmicBulletItem__VariantProps,
    internalArgProps: PlasmicBulletItem__ArgProps
  }
);

export default PlasmicBulletItem;
/* prettier-ignore-end */
