// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: mkraxK26DVUcftaRqUY3yk
// Component: AURlVeVjJ-Ho
import * as React from "react";

import * as p from "@plasmicapp/react-web";

import {
  hasVariant,
  classNames,
  wrapWithClassName,
  createPlasmicElementProxy,
  makeFragment,
  MultiChoiceArg,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  pick,
  omit,
  useTrigger,
  StrictProps,
  deriveRenderOpts,
  ensureGlobalVariants
} from "@plasmicapp/react-web";

import "@plasmicapp/react-web/lib/plasmic.css";
import * as defaultcss from "../plasmic__default_style.module.css"; // plasmic-import: global/defaultcss
import * as projectcss from "./plasmic_play_plasmic.module.css"; // plasmic-import: mkraxK26DVUcftaRqUY3yk/projectcss
import * as sty from "./PlasmicAccentButton.module.css"; // plasmic-import: AURlVeVjJ-Ho/css

export type PlasmicAccentButton__VariantMembers = {};

export type PlasmicAccentButton__VariantsArgs = {};
type VariantPropType = keyof PlasmicAccentButton__VariantsArgs;
export const PlasmicAccentButton__VariantProps = new Array<VariantPropType>();

export type PlasmicAccentButton__ArgsType = {};
type ArgPropType = keyof PlasmicAccentButton__ArgsType;
export const PlasmicAccentButton__ArgProps = new Array<ArgPropType>();

export type PlasmicAccentButton__OverridesType = {
  root?: p.Flex<"div">;
};

export interface DefaultAccentButtonProps {
  className?: string;
}

function PlasmicAccentButton__RenderFunc(props: {
  variants: PlasmicAccentButton__VariantsArgs;
  args: PlasmicAccentButton__ArgsType;
  overrides: PlasmicAccentButton__OverridesType;
  dataFetches?: PlasmicAccentButton__Fetches;
  forNode?: string;
}) {
  const { variants, args, overrides, forNode, dataFetches } = props;

  return (
    <div
      data-plasmic-name={"root"}
      data-plasmic-override={overrides.root}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      className={classNames(
        defaultcss.all,
        projectcss.all,
        defaultcss.__wab_text,
        projectcss.root_reset,
        sty.root
      )}
    >
      {"Click me"}
    </div>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: ["root"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  typeof PlasmicDescendants[T][number];
type NodeDefaultElementType = {
  root: "div";
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicAccentButton__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicAccentButton__VariantsArgs;
    args?: PlasmicAccentButton__ArgsType;
    overrides?: NodeOverridesType<T>;
    dataFetches?: PlasmicAccentButton__Fetches;
  } & Omit<PlasmicAccentButton__VariantsArgs, ReservedPropsType> & // Specify variants directly as props
    // Specify args directly as props
    Omit<PlasmicAccentButton__ArgsType, ReservedPropsType> &
    // Specify overrides for each element directly as props
    Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    // Specify props for the root element
    Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = deriveRenderOpts(props, {
      name: nodeName,
      descendantNames: [...PlasmicDescendants[nodeName]],
      internalArgPropNames: PlasmicAccentButton__ArgProps,
      internalVariantPropNames: PlasmicAccentButton__VariantProps
    });

    const { dataFetches } = props;

    return PlasmicAccentButton__RenderFunc({
      variants,
      args,
      overrides,
      dataFetches,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicAccentButton";
  } else {
    func.displayName = `PlasmicAccentButton.${nodeName}`;
  }
  return func;
}

export const PlasmicAccentButton = Object.assign(
  // Top-level PlasmicAccentButton renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements

    // Metadata about props expected for PlasmicAccentButton
    internalVariantProps: PlasmicAccentButton__VariantProps,
    internalArgProps: PlasmicAccentButton__ArgProps
  }
);

export default PlasmicAccentButton;
/* prettier-ignore-end */
