// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: mkraxK26DVUcftaRqUY3yk
// Component: qf7lDf5Z8vP9
import * as React from "react";

import * as p from "@plasmicapp/react-web";

import {
  hasVariant,
  classNames,
  wrapWithClassName,
  createPlasmicElementProxy,
  makeFragment,
  MultiChoiceArg,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  pick,
  omit,
  useTrigger,
  StrictProps,
  deriveRenderOpts,
  ensureGlobalVariants
} from "@plasmicapp/react-web";

import "@plasmicapp/react-web/lib/plasmic.css";
import * as defaultcss from "../plasmic__default_style.module.css"; // plasmic-import: global/defaultcss
import * as projectcss from "./plasmic_play_plasmic.module.css"; // plasmic-import: mkraxK26DVUcftaRqUY3yk/projectcss
import * as sty from "./PlasmicFiveStars.module.css"; // plasmic-import: qf7lDf5Z8vP9/css

import Icon10Icon from "./icons/PlasmicIcon__Icon10"; // plasmic-import: Y-ByPG89Cn3u/icon

export type PlasmicFiveStars__VariantMembers = {};

export type PlasmicFiveStars__VariantsArgs = {};
type VariantPropType = keyof PlasmicFiveStars__VariantsArgs;
export const PlasmicFiveStars__VariantProps = new Array<VariantPropType>();

export type PlasmicFiveStars__ArgsType = {};
type ArgPropType = keyof PlasmicFiveStars__ArgsType;
export const PlasmicFiveStars__ArgProps = new Array<ArgPropType>();

export type PlasmicFiveStars__OverridesType = {
  root?: p.Flex<"div">;
};

export interface DefaultFiveStarsProps {
  className?: string;
}

function PlasmicFiveStars__RenderFunc(props: {
  variants: PlasmicFiveStars__VariantsArgs;
  args: PlasmicFiveStars__ArgsType;
  overrides: PlasmicFiveStars__OverridesType;
  dataFetches?: PlasmicFiveStars__Fetches;
  forNode?: string;
}) {
  const { variants, args, overrides, forNode, dataFetches } = props;

  return (
    <p.Stack
      as={"div"}
      data-plasmic-name={"root"}
      data-plasmic-override={overrides.root}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      hasGap={true}
      className={classNames(
        defaultcss.all,
        projectcss.all,
        projectcss.root_reset,
        sty.root
      )}
    >
      <Icon10Icon
        className={classNames(defaultcss.all, projectcss.all, sty.svg__mFpxJ)}
        role={"img"}
      />

      <Icon10Icon
        className={classNames(defaultcss.all, projectcss.all, sty.svg__zdIw7)}
        role={"img"}
      />

      <Icon10Icon
        className={classNames(defaultcss.all, projectcss.all, sty.svg__e6JJd)}
        role={"img"}
      />

      <Icon10Icon
        className={classNames(defaultcss.all, projectcss.all, sty.svg__j35Qn)}
        role={"img"}
      />

      <Icon10Icon
        className={classNames(defaultcss.all, projectcss.all, sty.svg__a7HaT)}
        role={"img"}
      />
    </p.Stack>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: ["root"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  typeof PlasmicDescendants[T][number];
type NodeDefaultElementType = {
  root: "div";
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicFiveStars__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicFiveStars__VariantsArgs;
    args?: PlasmicFiveStars__ArgsType;
    overrides?: NodeOverridesType<T>;
    dataFetches?: PlasmicFiveStars__Fetches;
  } & Omit<PlasmicFiveStars__VariantsArgs, ReservedPropsType> & // Specify variants directly as props
    // Specify args directly as props
    Omit<PlasmicFiveStars__ArgsType, ReservedPropsType> &
    // Specify overrides for each element directly as props
    Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    // Specify props for the root element
    Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = deriveRenderOpts(props, {
      name: nodeName,
      descendantNames: [...PlasmicDescendants[nodeName]],
      internalArgPropNames: PlasmicFiveStars__ArgProps,
      internalVariantPropNames: PlasmicFiveStars__VariantProps
    });

    const { dataFetches } = props;

    return PlasmicFiveStars__RenderFunc({
      variants,
      args,
      overrides,
      dataFetches,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicFiveStars";
  } else {
    func.displayName = `PlasmicFiveStars.${nodeName}`;
  }
  return func;
}

export const PlasmicFiveStars = Object.assign(
  // Top-level PlasmicFiveStars renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements

    // Metadata about props expected for PlasmicFiveStars
    internalVariantProps: PlasmicFiveStars__VariantProps,
    internalArgProps: PlasmicFiveStars__ArgProps
  }
);

export default PlasmicFiveStars;
/* prettier-ignore-end */
