// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: mkraxK26DVUcftaRqUY3yk
// Component: vz6doh95LBs
import * as React from "react";

import * as p from "@plasmicapp/react-web";

import {
  hasVariant,
  classNames,
  wrapWithClassName,
  createPlasmicElementProxy,
  makeFragment,
  MultiChoiceArg,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  pick,
  omit,
  useTrigger,
  StrictProps,
  deriveRenderOpts,
  ensureGlobalVariants
} from "@plasmicapp/react-web";

import "@plasmicapp/react-web/lib/plasmic.css";
import * as defaultcss from "../plasmic__default_style.module.css"; // plasmic-import: global/defaultcss
import * as projectcss from "./plasmic_play_plasmic.module.css"; // plasmic-import: mkraxK26DVUcftaRqUY3yk/projectcss
import * as sty from "./PlasmicCompletedTweet.module.css"; // plasmic-import: vz6doh95LBs/css

import CommentIcon from "./icons/PlasmicIcon__Comment"; // plasmic-import: G1QeSUusjchd/icon
import RefreshIcon from "./icons/PlasmicIcon__Refresh"; // plasmic-import: tdoBjOA2BxEV/icon
import HeartIcon from "./icons/PlasmicIcon__Heart"; // plasmic-import: pjpx1ObBaN_F/icon
import UploadIcon from "./icons/PlasmicIcon__Upload"; // plasmic-import: V2V4D7mhiIko/icon

export type PlasmicCompletedTweet__VariantMembers = {};

export type PlasmicCompletedTweet__VariantsArgs = {};
type VariantPropType = keyof PlasmicCompletedTweet__VariantsArgs;
export const PlasmicCompletedTweet__VariantProps = new Array<VariantPropType>();

export type PlasmicCompletedTweet__ArgsType = {};
type ArgPropType = keyof PlasmicCompletedTweet__ArgsType;
export const PlasmicCompletedTweet__ArgProps = new Array<ArgPropType>();

export type PlasmicCompletedTweet__OverridesType = {
  root?: p.Flex<"div">;
  img?: p.Flex<typeof p.PlasmicImg>;
};

export interface DefaultCompletedTweetProps {
  className?: string;
}

function PlasmicCompletedTweet__RenderFunc(props: {
  variants: PlasmicCompletedTweet__VariantsArgs;
  args: PlasmicCompletedTweet__ArgsType;
  overrides: PlasmicCompletedTweet__OverridesType;
  dataFetches?: PlasmicCompletedTweet__Fetches;
  forNode?: string;
}) {
  const { variants, args, overrides, forNode, dataFetches } = props;

  return (
    <p.Stack
      as={"div"}
      data-plasmic-name={"root"}
      data-plasmic-override={overrides.root}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      hasGap={true}
      className={classNames(
        defaultcss.all,
        projectcss.all,
        projectcss.root_reset,
        sty.root
      )}
    >
      <p.PlasmicImg
        data-plasmic-name={"img"}
        data-plasmic-override={overrides.img}
        alt={""}
        className={classNames(sty.img)}
        displayHeight={"64px" as const}
        displayMaxHeight={"none" as const}
        displayMaxWidth={"none" as const}
        displayMinHeight={"0" as const}
        displayMinWidth={"0" as const}
        displayWidth={"64px" as const}
      />

      <p.Stack
        as={"div"}
        hasGap={true}
        className={classNames(
          defaultcss.all,
          projectcss.all,
          sty.freeBox__ubVpK
        )}
      >
        <div
          className={classNames(
            defaultcss.all,
            projectcss.all,
            defaultcss.__wab_text,
            sty.text__uyYg
          )}
        >
          {"Mark Dalgleish"}
        </div>

        <div
          className={classNames(
            defaultcss.all,
            projectcss.all,
            defaultcss.__wab_text,
            sty.text__ytSeF
          )}
        >
          {
            "Other industries figured out a long time ago that you can't go straight from concept design to construction. If we want to do design systems right, we're missing a step."
          }
        </div>

        <p.Stack
          as={"div"}
          hasGap={true}
          className={classNames(
            defaultcss.all,
            projectcss.all,
            sty.freeBox__sMtQf
          )}
        >
          <CommentIcon
            className={classNames(
              defaultcss.all,
              projectcss.all,
              sty.svg__opvvb
            )}
            role={"img"}
          />

          <RefreshIcon
            className={classNames(
              defaultcss.all,
              projectcss.all,
              sty.svg__ir5GR
            )}
            role={"img"}
          />

          <HeartIcon
            className={classNames(
              defaultcss.all,
              projectcss.all,
              sty.svg__tg8Td
            )}
            role={"img"}
          />

          <UploadIcon
            className={classNames(
              defaultcss.all,
              projectcss.all,
              sty.svg__ycw3D
            )}
            role={"img"}
          />
        </p.Stack>
      </p.Stack>
    </p.Stack>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: ["root", "img"],
  img: ["img"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  typeof PlasmicDescendants[T][number];
type NodeDefaultElementType = {
  root: "div";
  img: typeof p.PlasmicImg;
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicCompletedTweet__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicCompletedTweet__VariantsArgs;
    args?: PlasmicCompletedTweet__ArgsType;
    overrides?: NodeOverridesType<T>;
    dataFetches?: PlasmicCompletedTweet__Fetches;
  } & Omit<PlasmicCompletedTweet__VariantsArgs, ReservedPropsType> & // Specify variants directly as props
    // Specify args directly as props
    Omit<PlasmicCompletedTweet__ArgsType, ReservedPropsType> &
    // Specify overrides for each element directly as props
    Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    // Specify props for the root element
    Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = deriveRenderOpts(props, {
      name: nodeName,
      descendantNames: [...PlasmicDescendants[nodeName]],
      internalArgPropNames: PlasmicCompletedTweet__ArgProps,
      internalVariantPropNames: PlasmicCompletedTweet__VariantProps
    });

    const { dataFetches } = props;

    return PlasmicCompletedTweet__RenderFunc({
      variants,
      args,
      overrides,
      dataFetches,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicCompletedTweet";
  } else {
    func.displayName = `PlasmicCompletedTweet.${nodeName}`;
  }
  return func;
}

export const PlasmicCompletedTweet = Object.assign(
  // Top-level PlasmicCompletedTweet renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    img: makeNodeComponent("img"),

    // Metadata about props expected for PlasmicCompletedTweet
    internalVariantProps: PlasmicCompletedTweet__VariantProps,
    internalArgProps: PlasmicCompletedTweet__ArgProps
  }
);

export default PlasmicCompletedTweet;
/* prettier-ignore-end */
