// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: mkraxK26DVUcftaRqUY3yk
// Component: 1T1DHjJON3EE
import * as React from "react";

import * as p from "@plasmicapp/react-web";

import {
  hasVariant,
  classNames,
  wrapWithClassName,
  createPlasmicElementProxy,
  makeFragment,
  MultiChoiceArg,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  pick,
  omit,
  useTrigger,
  StrictProps,
  deriveRenderOpts,
  ensureGlobalVariants
} from "@plasmicapp/react-web";

import "@plasmicapp/react-web/lib/plasmic.css";
import * as defaultcss from "../plasmic__default_style.module.css"; // plasmic-import: global/defaultcss
import * as projectcss from "./plasmic_play_plasmic.module.css"; // plasmic-import: mkraxK26DVUcftaRqUY3yk/projectcss
import * as sty from "./PlasmicInteractionButton.module.css"; // plasmic-import: 1T1DHjJON3EE/css

export type PlasmicInteractionButton__VariantMembers = {};

export type PlasmicInteractionButton__VariantsArgs = {};
type VariantPropType = keyof PlasmicInteractionButton__VariantsArgs;
export const PlasmicInteractionButton__VariantProps =
  new Array<VariantPropType>();

export type PlasmicInteractionButton__ArgsType = {};
type ArgPropType = keyof PlasmicInteractionButton__ArgsType;
export const PlasmicInteractionButton__ArgProps = new Array<ArgPropType>();

export type PlasmicInteractionButton__OverridesType = {
  root?: p.Flex<"button">;
};

export interface DefaultInteractionButtonProps {
  className?: string;
}

function PlasmicInteractionButton__RenderFunc(props: {
  variants: PlasmicInteractionButton__VariantsArgs;
  args: PlasmicInteractionButton__ArgsType;
  overrides: PlasmicInteractionButton__OverridesType;
  dataFetches?: PlasmicInteractionButton__Fetches;
  forNode?: string;
}) {
  const { variants, args, overrides, forNode, dataFetches } = props;

  return (
    <button
      data-plasmic-name={"root"}
      data-plasmic-override={overrides.root}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      className={classNames(
        defaultcss.button,
        projectcss.button,
        defaultcss.__wab_text,
        projectcss.root_reset,
        sty.root
      )}
    >
      {"Click me"}
    </button>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: ["root"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  typeof PlasmicDescendants[T][number];
type NodeDefaultElementType = {
  root: "button";
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicInteractionButton__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicInteractionButton__VariantsArgs;
    args?: PlasmicInteractionButton__ArgsType;
    overrides?: NodeOverridesType<T>;
    dataFetches?: PlasmicInteractionButton__Fetches;
  } & Omit<PlasmicInteractionButton__VariantsArgs, ReservedPropsType> & // Specify variants directly as props
    // Specify args directly as props
    Omit<PlasmicInteractionButton__ArgsType, ReservedPropsType> &
    // Specify overrides for each element directly as props
    Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    // Specify props for the root element
    Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = deriveRenderOpts(props, {
      name: nodeName,
      descendantNames: [...PlasmicDescendants[nodeName]],
      internalArgPropNames: PlasmicInteractionButton__ArgProps,
      internalVariantPropNames: PlasmicInteractionButton__VariantProps
    });

    const { dataFetches } = props;

    return PlasmicInteractionButton__RenderFunc({
      variants,
      args,
      overrides,
      dataFetches,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicInteractionButton";
  } else {
    func.displayName = `PlasmicInteractionButton.${nodeName}`;
  }
  return func;
}

export const PlasmicInteractionButton = Object.assign(
  // Top-level PlasmicInteractionButton renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements

    // Metadata about props expected for PlasmicInteractionButton
    internalVariantProps: PlasmicInteractionButton__VariantProps,
    internalArgProps: PlasmicInteractionButton__ArgProps
  }
);

export default PlasmicInteractionButton;
/* prettier-ignore-end */
