// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: mkraxK26DVUcftaRqUY3yk
// Component: zDyPLqQy14hx
import * as React from "react";

import * as p from "@plasmicapp/react-web";

import {
  hasVariant,
  classNames,
  wrapWithClassName,
  createPlasmicElementProxy,
  makeFragment,
  MultiChoiceArg,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  pick,
  omit,
  useTrigger,
  StrictProps,
  deriveRenderOpts,
  ensureGlobalVariants
} from "@plasmicapp/react-web";

import "@plasmicapp/react-web/lib/plasmic.css";
import * as defaultcss from "../plasmic__default_style.module.css"; // plasmic-import: global/defaultcss
import * as projectcss from "./plasmic_play_plasmic.module.css"; // plasmic-import: mkraxK26DVUcftaRqUY3yk/projectcss
import * as sty from "./PlasmicCompletedLandmarks.module.css"; // plasmic-import: zDyPLqQy14hx/css

import Icon12Icon from "./icons/PlasmicIcon__Icon12"; // plasmic-import: nPmRp3GbB80G/icon

export type PlasmicCompletedLandmarks__VariantMembers = {
  variants: "wide";
};

export type PlasmicCompletedLandmarks__VariantsArgs = {
  variants?: SingleChoiceArg<"wide">;
};

type VariantPropType = keyof PlasmicCompletedLandmarks__VariantsArgs;
export const PlasmicCompletedLandmarks__VariantProps =
  new Array<VariantPropType>("variants");

export type PlasmicCompletedLandmarks__ArgsType = {};
type ArgPropType = keyof PlasmicCompletedLandmarks__ArgsType;
export const PlasmicCompletedLandmarks__ArgProps = new Array<ArgPropType>();

export type PlasmicCompletedLandmarks__OverridesType = {
  root?: p.Flex<"div">;
};

export interface DefaultCompletedLandmarksProps {
  variants?: SingleChoiceArg<"wide">;
  className?: string;
}

function PlasmicCompletedLandmarks__RenderFunc(props: {
  variants: PlasmicCompletedLandmarks__VariantsArgs;
  args: PlasmicCompletedLandmarks__ArgsType;
  overrides: PlasmicCompletedLandmarks__OverridesType;
  dataFetches?: PlasmicCompletedLandmarks__Fetches;
  forNode?: string;
}) {
  const { variants, args, overrides, forNode, dataFetches } = props;

  return (
    <div
      data-plasmic-name={"root"}
      data-plasmic-override={overrides.root}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      className={classNames(
        defaultcss.all,
        projectcss.all,
        projectcss.root_reset,
        sty.root,
        { [sty.root__variants_wide]: hasVariant(variants, "variants", "wide") }
      )}
    >
      <div
        className={classNames(
          defaultcss.all,
          projectcss.all,
          defaultcss.__wab_text,
          sty.text__caM03,
          {
            [sty.text__variants_wide__caM03Eeld8]: hasVariant(
              variants,
              "variants",
              "wide"
            )
          }
        )}
      >
        {"Landmarks"}
      </div>

      <p.Stack
        as={"div"}
        hasGap={true}
        className={classNames(
          defaultcss.all,
          projectcss.all,
          sty.freeBox___9JLqK,
          {
            [sty.freeBox__variants_wide___9JLqKeeld8]: hasVariant(
              variants,
              "variants",
              "wide"
            )
          }
        )}
      >
        <div
          className={classNames(
            defaultcss.all,
            projectcss.all,
            sty.freeBox__aayuD,
            {
              [sty.freeBox__variants_wide__aayuDeeld8]: hasVariant(
                variants,
                "variants",
                "wide"
              )
            }
          )}
        >
          <div
            className={classNames(
              defaultcss.all,
              projectcss.all,
              defaultcss.__wab_text,
              sty.text__irmz9
            )}
          >
            {"Mission Dolores Park"}
          </div>

          <div
            className={classNames(
              defaultcss.all,
              projectcss.all,
              defaultcss.__wab_text,
              sty.text___3QOQt
            )}
          >
            {"Park"}
          </div>

          <Icon12Icon
            className={classNames(
              defaultcss.all,
              projectcss.all,
              sty.svg__agZoG
            )}
            role={"img"}
          />
        </div>

        <div
          className={classNames(
            defaultcss.all,
            projectcss.all,
            sty.freeBox__mJer,
            {
              [sty.freeBox__variants_wide__mJerEeld8]: hasVariant(
                variants,
                "variants",
                "wide"
              )
            }
          )}
        >
          <div
            className={classNames(
              defaultcss.all,
              projectcss.all,
              defaultcss.__wab_text,
              sty.text__m9D6O,
              {
                [sty.text__variants_wide__m9D6OEeld8]: hasVariant(
                  variants,
                  "variants",
                  "wide"
                )
              }
            )}
          >
            {"Mission Dolores Park"}
          </div>

          <div
            className={classNames(
              defaultcss.all,
              projectcss.all,
              defaultcss.__wab_text,
              sty.text__qr0I1
            )}
          >
            {"Park"}
          </div>

          <Icon12Icon
            className={classNames(
              defaultcss.all,
              projectcss.all,
              sty.svg___5Rd1
            )}
            role={"img"}
          />
        </div>

        <div
          className={classNames(
            defaultcss.all,
            projectcss.all,
            sty.freeBox__rwHxx,
            {
              [sty.freeBox__variants_wide__rwHxxeeld8]: hasVariant(
                variants,
                "variants",
                "wide"
              )
            }
          )}
        >
          <div
            className={classNames(
              defaultcss.all,
              projectcss.all,
              defaultcss.__wab_text,
              sty.text__fwsqa
            )}
          >
            {"Mission Dolores Park"}
          </div>

          <div
            className={classNames(
              defaultcss.all,
              projectcss.all,
              defaultcss.__wab_text,
              sty.text__wH2Qg
            )}
          >
            {"Park"}
          </div>

          <Icon12Icon
            className={classNames(
              defaultcss.all,
              projectcss.all,
              sty.svg__j5X91
            )}
            role={"img"}
          />
        </div>
      </p.Stack>
    </div>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: ["root"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  typeof PlasmicDescendants[T][number];
type NodeDefaultElementType = {
  root: "div";
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicCompletedLandmarks__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicCompletedLandmarks__VariantsArgs;
    args?: PlasmicCompletedLandmarks__ArgsType;
    overrides?: NodeOverridesType<T>;
    dataFetches?: PlasmicCompletedLandmarks__Fetches;
  } & Omit<PlasmicCompletedLandmarks__VariantsArgs, ReservedPropsType> & // Specify variants directly as props
    // Specify args directly as props
    Omit<PlasmicCompletedLandmarks__ArgsType, ReservedPropsType> &
    // Specify overrides for each element directly as props
    Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    // Specify props for the root element
    Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = deriveRenderOpts(props, {
      name: nodeName,
      descendantNames: [...PlasmicDescendants[nodeName]],
      internalArgPropNames: PlasmicCompletedLandmarks__ArgProps,
      internalVariantPropNames: PlasmicCompletedLandmarks__VariantProps
    });

    const { dataFetches } = props;

    return PlasmicCompletedLandmarks__RenderFunc({
      variants,
      args,
      overrides,
      dataFetches,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicCompletedLandmarks";
  } else {
    func.displayName = `PlasmicCompletedLandmarks.${nodeName}`;
  }
  return func;
}

export const PlasmicCompletedLandmarks = Object.assign(
  // Top-level PlasmicCompletedLandmarks renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements

    // Metadata about props expected for PlasmicCompletedLandmarks
    internalVariantProps: PlasmicCompletedLandmarks__VariantProps,
    internalArgProps: PlasmicCompletedLandmarks__ArgProps
  }
);

export default PlasmicCompletedLandmarks;
/* prettier-ignore-end */
