// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: mkraxK26DVUcftaRqUY3yk
// Component: xhf7eLvFPSn
import * as React from "react";

import * as p from "@plasmicapp/react-web";

import {
  hasVariant,
  classNames,
  wrapWithClassName,
  createPlasmicElementProxy,
  makeFragment,
  MultiChoiceArg,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  pick,
  omit,
  useTrigger,
  StrictProps,
  deriveRenderOpts,
  ensureGlobalVariants
} from "@plasmicapp/react-web";

import "@plasmicapp/react-web/lib/plasmic.css";
import * as defaultcss from "../plasmic__default_style.module.css"; // plasmic-import: global/defaultcss
import * as projectcss from "./plasmic_play_plasmic.module.css"; // plasmic-import: mkraxK26DVUcftaRqUY3yk/projectcss
import * as sty from "./PlasmicCompletedTask2.module.css"; // plasmic-import: xhf7eLvFPSn/css

export type PlasmicCompletedTask2__VariantMembers = {};

export type PlasmicCompletedTask2__VariantsArgs = {};
type VariantPropType = keyof PlasmicCompletedTask2__VariantsArgs;
export const PlasmicCompletedTask2__VariantProps = new Array<VariantPropType>();

export type PlasmicCompletedTask2__ArgsType = {
  children?: React.ReactNode;
};

type ArgPropType = keyof PlasmicCompletedTask2__ArgsType;
export const PlasmicCompletedTask2__ArgProps = new Array<ArgPropType>(
  "children"
);

export type PlasmicCompletedTask2__OverridesType = {
  root?: p.Flex<"div">;
  freeBox?: p.Flex<"div">;
};

export interface DefaultCompletedTask2Props {
  children?: React.ReactNode;
  className?: string;
}

function PlasmicCompletedTask2__RenderFunc(props: {
  variants: PlasmicCompletedTask2__VariantsArgs;
  args: PlasmicCompletedTask2__ArgsType;
  overrides: PlasmicCompletedTask2__OverridesType;
  dataFetches?: PlasmicCompletedTask2__Fetches;
  forNode?: string;
}) {
  const { variants, args, overrides, forNode, dataFetches } = props;

  return (
    <p.Stack
      as={"div"}
      data-plasmic-name={"root"}
      data-plasmic-override={overrides.root}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      hasGap={true}
      className={classNames(
        defaultcss.all,
        projectcss.all,
        projectcss.root_reset,
        sty.root
      )}
    >
      <div
        data-plasmic-name={"freeBox"}
        data-plasmic-override={overrides.freeBox}
        className={classNames(defaultcss.all, projectcss.all, sty.freeBox)}
      />

      {p.renderPlasmicSlot({
        defaultContents: "Request application extension",
        value: args.children,
        className: classNames(sty.slotTargetChildren)
      })}
    </p.Stack>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: ["root", "freeBox"],
  freeBox: ["freeBox"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  typeof PlasmicDescendants[T][number];
type NodeDefaultElementType = {
  root: "div";
  freeBox: "div";
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicCompletedTask2__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicCompletedTask2__VariantsArgs;
    args?: PlasmicCompletedTask2__ArgsType;
    overrides?: NodeOverridesType<T>;
    dataFetches?: PlasmicCompletedTask2__Fetches;
  } & Omit<PlasmicCompletedTask2__VariantsArgs, ReservedPropsType> & // Specify variants directly as props
    // Specify args directly as props
    Omit<PlasmicCompletedTask2__ArgsType, ReservedPropsType> &
    // Specify overrides for each element directly as props
    Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    // Specify props for the root element
    Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = deriveRenderOpts(props, {
      name: nodeName,
      descendantNames: [...PlasmicDescendants[nodeName]],
      internalArgPropNames: PlasmicCompletedTask2__ArgProps,
      internalVariantPropNames: PlasmicCompletedTask2__VariantProps
    });

    const { dataFetches } = props;

    return PlasmicCompletedTask2__RenderFunc({
      variants,
      args,
      overrides,
      dataFetches,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicCompletedTask2";
  } else {
    func.displayName = `PlasmicCompletedTask2.${nodeName}`;
  }
  return func;
}

export const PlasmicCompletedTask2 = Object.assign(
  // Top-level PlasmicCompletedTask2 renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    freeBox: makeNodeComponent("freeBox"),

    // Metadata about props expected for PlasmicCompletedTask2
    internalVariantProps: PlasmicCompletedTask2__VariantProps,
    internalArgProps: PlasmicCompletedTask2__ArgProps
  }
);

export default PlasmicCompletedTask2;
/* prettier-ignore-end */
