// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: mkraxK26DVUcftaRqUY3yk
// Component: MTwEWXgSnHbk
import * as React from "react";

import * as p from "@plasmicapp/react-web";

import {
  hasVariant,
  classNames,
  wrapWithClassName,
  createPlasmicElementProxy,
  makeFragment,
  MultiChoiceArg,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  pick,
  omit,
  useTrigger,
  StrictProps,
  deriveRenderOpts,
  ensureGlobalVariants
} from "@plasmicapp/react-web";

import "@plasmicapp/react-web/lib/plasmic.css";
import * as defaultcss from "../plasmic__default_style.module.css"; // plasmic-import: global/defaultcss
import * as projectcss from "./plasmic_play_plasmic.module.css"; // plasmic-import: mkraxK26DVUcftaRqUY3yk/projectcss
import * as sty from "./PlasmicCompletedTestimonial2.module.css"; // plasmic-import: MTwEWXgSnHbk/css

import Icon28Icon from "./icons/PlasmicIcon__Icon28"; // plasmic-import: zuLiKym3ObVu/icon
import image45EIfTYhYfQhu from "./images/image45.png"; // plasmic-import: EIfT_YhYfQhu/picture

export type PlasmicCompletedTestimonial2__VariantMembers = {};

export type PlasmicCompletedTestimonial2__VariantsArgs = {};
type VariantPropType = keyof PlasmicCompletedTestimonial2__VariantsArgs;
export const PlasmicCompletedTestimonial2__VariantProps =
  new Array<VariantPropType>();

export type PlasmicCompletedTestimonial2__ArgsType = {
  children?: React.ReactNode;
  slot2?: React.ReactNode;
  slot3?: React.ReactNode;
  slot?: React.ReactNode;
};

type ArgPropType = keyof PlasmicCompletedTestimonial2__ArgsType;
export const PlasmicCompletedTestimonial2__ArgProps = new Array<ArgPropType>(
  "children",
  "slot2",
  "slot3",
  "slot"
);

export type PlasmicCompletedTestimonial2__OverridesType = {
  root?: p.Flex<"div">;
  svg?: p.Flex<"svg">;
};

export interface DefaultCompletedTestimonial2Props {
  children?: React.ReactNode;
  slot2?: React.ReactNode;
  slot3?: React.ReactNode;
  slot?: React.ReactNode;
  className?: string;
}

function PlasmicCompletedTestimonial2__RenderFunc(props: {
  variants: PlasmicCompletedTestimonial2__VariantsArgs;
  args: PlasmicCompletedTestimonial2__ArgsType;
  overrides: PlasmicCompletedTestimonial2__OverridesType;
  dataFetches?: PlasmicCompletedTestimonial2__Fetches;
  forNode?: string;
}) {
  const { variants, args, overrides, forNode, dataFetches } = props;

  return (
    <p.Stack
      as={"div"}
      data-plasmic-name={"root"}
      data-plasmic-override={overrides.root}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      hasGap={true}
      className={classNames(
        defaultcss.all,
        projectcss.all,
        projectcss.root_reset,
        sty.root
      )}
    >
      <div
        className={classNames(
          defaultcss.all,
          projectcss.all,
          sty.freeBox__wINmw
        )}
      >
        {p.renderPlasmicSlot({
          defaultContents: (
            <p.PlasmicImg
              alt={""}
              className={classNames(sty.img___5Qddm)}
              displayHeight={"100px" as const}
              displayMaxHeight={"none" as const}
              displayMaxWidth={"none" as const}
              displayMinHeight={"0" as const}
              displayMinWidth={"0" as const}
              displayWidth={"100px" as const}
              src={{
                src: image45EIfTYhYfQhu,
                fullWidth: 205,
                fullHeight: 208,
                aspectRatio: undefined
              }}
            />
          ),

          value: args.slot
        })}
      </div>

      <Icon28Icon
        data-plasmic-name={"svg"}
        data-plasmic-override={overrides.svg}
        className={classNames(defaultcss.all, projectcss.all, sty.svg)}
        role={"img"}
      />

      <div
        className={classNames(
          defaultcss.all,
          projectcss.all,
          sty.freeBox__ke5Ok
        )}
      >
        <div
          className={classNames(
            defaultcss.all,
            projectcss.all,
            sty.freeBox__nX31T
          )}
        >
          {p.renderPlasmicSlot({
            defaultContents: "Truly revolutionary. An incredible leap forward.",
            value: args.children,
            className: classNames(sty.slotTargetChildren)
          })}
        </div>
      </div>

      <p.Stack
        as={"div"}
        hasGap={true}
        className={classNames(
          defaultcss.all,
          projectcss.all,
          sty.freeBox__gnUQl
        )}
      >
        <div
          className={classNames(
            defaultcss.all,
            projectcss.all,
            sty.freeBox__rgHo9
          )}
        >
          {p.renderPlasmicSlot({
            defaultContents: "Jane Doe",
            value: args.slot2,
            className: classNames(sty.slotTargetSlot2)
          })}

          {p.renderPlasmicSlot({
            defaultContents: "VP Marketing\nPied Piper",
            value: args.slot3,
            className: classNames(sty.slotTargetSlot3)
          })}
        </div>
      </p.Stack>
    </p.Stack>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: ["root", "svg"],
  svg: ["svg"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  typeof PlasmicDescendants[T][number];
type NodeDefaultElementType = {
  root: "div";
  svg: "svg";
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicCompletedTestimonial2__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicCompletedTestimonial2__VariantsArgs;
    args?: PlasmicCompletedTestimonial2__ArgsType;
    overrides?: NodeOverridesType<T>;
    dataFetches?: PlasmicCompletedTestimonial2__Fetches;
  } & Omit<PlasmicCompletedTestimonial2__VariantsArgs, ReservedPropsType> & // Specify variants directly as props
    // Specify args directly as props
    Omit<PlasmicCompletedTestimonial2__ArgsType, ReservedPropsType> &
    // Specify overrides for each element directly as props
    Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    // Specify props for the root element
    Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = deriveRenderOpts(props, {
      name: nodeName,
      descendantNames: [...PlasmicDescendants[nodeName]],
      internalArgPropNames: PlasmicCompletedTestimonial2__ArgProps,
      internalVariantPropNames: PlasmicCompletedTestimonial2__VariantProps
    });

    const { dataFetches } = props;

    return PlasmicCompletedTestimonial2__RenderFunc({
      variants,
      args,
      overrides,
      dataFetches,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicCompletedTestimonial2";
  } else {
    func.displayName = `PlasmicCompletedTestimonial2.${nodeName}`;
  }
  return func;
}

export const PlasmicCompletedTestimonial2 = Object.assign(
  // Top-level PlasmicCompletedTestimonial2 renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    svg: makeNodeComponent("svg"),

    // Metadata about props expected for PlasmicCompletedTestimonial2
    internalVariantProps: PlasmicCompletedTestimonial2__VariantProps,
    internalArgProps: PlasmicCompletedTestimonial2__ArgProps
  }
);

export default PlasmicCompletedTestimonial2;
/* prettier-ignore-end */
