// This is a skeleton starter React component generated by Plasmic.
// This file is owned by you, feel free to edit as you see fit.
import * as React from "react";
import {
  PlasmicCompletedButton5,
  DefaultCompletedButton5Props
} from "./plasmic/play_plasmic/PlasmicCompletedButton5";
import { HTMLElementRefOf } from "@plasmicapp/react-web";

// Your component props start with props for variants and slots you defined
// in Plasmic, but you can add more here, like event handlers that you can
// attach to named nodes in your component.
//
// If you don't want to expose certain variants or slots as a prop, you can use
// Omit to hide them:
//
// interface CompletedButton5Props extends Omit<DefaultCompletedButton5Props, "hideProps1"|"hideProp2"> {
//   // etc.
// }
//
// You can also stop extending from DefaultCompletedButton5Props altogether and have
// total control over the props for your component.
interface CompletedButton5Props extends DefaultCompletedButton5Props {}

function CompletedButton5_(
  props: CompletedButton5Props,
  ref: HTMLElementRefOf<"div">
) {
  // Use PlasmicCompletedButton5 to render this component as it was
  // designed in Plasmic, by activating the appropriate variants,
  // attaching the appropriate event handlers, etc.  You
  // can also install whatever React hooks you need here to manage state or
  // fetch data.
  //
  // Props you can pass into PlasmicCompletedButton5 are:
  // 1. Variants you want to activate,
  // 2. Contents for slots you want to fill,
  // 3. Overrides for any named node in the component to attach behavior and data,
  // 4. Props to set on the root node.
  //
  // By default, we are just piping all CompletedButton5Props here, but feel free
  // to do whatever works for you.

  return <PlasmicCompletedButton5 root={{ ref }} {...props} />;
}

const CompletedButton5 = React.forwardRef(CompletedButton5_);
export default CompletedButton5;
