// This is a skeleton starter React component generated by Plasmic.
// This file is owned by you, feel free to edit as you see fit.
import * as React from "react";
import {
  PlasmicCompletedAccentButton,
  DefaultCompletedAccentButtonProps
} from "./plasmic/play_plasmic/PlasmicCompletedAccentButton";
import { HTMLElementRefOf } from "@plasmicapp/react-web";

// Your component props start with props for variants and slots you defined
// in Plasmic, but you can add more here, like event handlers that you can
// attach to named nodes in your component.
//
// If you don't want to expose certain variants or slots as a prop, you can use
// Omit to hide them:
//
// interface CompletedAccentButtonProps extends Omit<DefaultCompletedAccentButtonProps, "hideProps1"|"hideProp2"> {
//   // etc.
// }
//
// You can also stop extending from DefaultCompletedAccentButtonProps altogether and have
// total control over the props for your component.
interface CompletedAccentButtonProps
  extends DefaultCompletedAccentButtonProps {}

function CompletedAccentButton_(
  props: CompletedAccentButtonProps,
  ref: HTMLElementRefOf<"div">
) {
  // Use PlasmicCompletedAccentButton to render this component as it was
  // designed in Plasmic, by activating the appropriate variants,
  // attaching the appropriate event handlers, etc.  You
  // can also install whatever React hooks you need here to manage state or
  // fetch data.
  //
  // Props you can pass into PlasmicCompletedAccentButton are:
  // 1. Variants you want to activate,
  // 2. Contents for slots you want to fill,
  // 3. Overrides for any named node in the component to attach behavior and data,
  // 4. Props to set on the root node.
  //
  // By default, we are just piping all CompletedAccentButtonProps here, but feel free
  // to do whatever works for you.

  return <PlasmicCompletedAccentButton root={{ ref }} {...props} />;
}

const CompletedAccentButton = React.forwardRef(CompletedAccentButton_);
export default CompletedAccentButton;
