// This is a skeleton starter React component generated by Plasmic.
// This file is owned by you, feel free to edit as you see fit.
import * as React from "react";
import {
  PlasmicForecast,
  DefaultForecastProps
} from "./plasmic/play_plasmic/PlasmicForecast";
import { HTMLElementRefOf } from "@plasmicapp/react-web";

// Your component props start with props for variants and slots you defined
// in Plasmic, but you can add more here, like event handlers that you can
// attach to named nodes in your component.
//
// If you don't want to expose certain variants or slots as a prop, you can use
// Omit to hide them:
//
// interface ForecastProps extends Omit<DefaultForecastProps, "hideProps1"|"hideProp2"> {
//   // etc.
// }
//
// You can also stop extending from DefaultForecastProps altogether and have
// total control over the props for your component.
interface ForecastProps extends DefaultForecastProps {}

function Forecast_(props: ForecastProps, ref: HTMLElementRefOf<"div">) {
  // Use PlasmicForecast to render this component as it was
  // designed in Plasmic, by activating the appropriate variants,
  // attaching the appropriate event handlers, etc.  You
  // can also install whatever React hooks you need here to manage state or
  // fetch data.
  //
  // Props you can pass into PlasmicForecast are:
  // 1. Variants you want to activate,
  // 2. Contents for slots you want to fill,
  // 3. Overrides for any named node in the component to attach behavior and data,
  // 4. Props to set on the root node.
  //
  // By default, we are just piping all ForecastProps here, but feel free
  // to do whatever works for you.

  return <PlasmicForecast root={{ ref }} {...props} />;
}

const Forecast = React.forwardRef(Forecast_);
export default Forecast;
